services:
  db:
    image: bitnami/postgresql:latest
    container_name: poke-container-db
    user: root
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pokedb
      - BITNAMI_DEBUG=true
    ports:
      - "5432:5432"
    volumes:
      - pg_data_final:/bitnami/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: poke-container-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/pokedb            
      - DB_HOST=db
      - DB_NAME=pokedb
      - DB_USER=admin
      - DB_PASS=admin
      - DB_PORT=5432

volumes:
  pg_data_final:
    driver: local